# Generated by Django 3.1.3 on 2021-04-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('o1', models.CharField(max_length=40)),
                ('o2', models.CharField(max_length=40)),
                ('o3', models.CharField(max_length=40)),
                ('o4', models.CharField(max_length=40)),
                ('total_votes', models.TextField()),
                ('o1_votes', models.TextField()),
                ('o2_votes', models.TextField()),
                ('o3_votes', models.TextField()),
                ('o4_votes', models.TextField()),
            ],
        ),
    ]
