# Generated by Django 3.1.3 on 2021-04-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210416_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
